-- ============================================================
-- WBH Product Catalog — Full Migration with Images
-- Run this in your Supabase SQL Editor
-- Replaces old PRD-xxx products with new PROD-xxx products
-- ============================================================

-- Step 1: Add image columns if they don't exist
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url_2 TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS image_url_3 TEXT;

-- Step 2: Delete old seed data (PRD-xxx IDs)
DELETE FROM public.recommendation_items WHERE product_id LIKE 'PRD-%';
DELETE FROM public.products WHERE id LIKE 'PRD-%';

-- Step 3: Insert all updated products
-- ==========================================
-- Cleansers (CAT-06)
-- ==========================================
INSERT INTO public.products (id, category_id, category_name, product_name, brand, sub_type, finish, best_for, confidence_level, skin_concern_tags, image_url, image_url_2, image_url_3) VALUES
('PROD-001', 'CAT-06', 'Cleansers', 'Skin By Zaron Vitamin C Brightening Body Wash', 'Skin By Zaron', 'Body Wash', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Skin-By-Zaron-Vitamin-C-Brightening-Body-Wash.jpg', NULL, NULL),
('PROD-002', 'CAT-06', 'Cleansers', 'Skin By Zaron Micellar Cleansing Water', 'Skin By Zaron', 'Cleanser', 'Gentle', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Skin-By-Zaron-Micellar-Cleansing-Water.jpg', NULL, NULL),
('PROD-006', 'CAT-06', 'Cleansers', 'Skin By Zaron Exfoliating & Brightening Face Wash', 'Skin By Zaron', 'Face Wash', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/IMG-0020.webp', NULL, NULL),
('PROD-007', 'CAT-06', 'Cleansers', 'Skin By Zaron Acne Control Glow Wash', 'Skin By Zaron', 'Face Wash', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Skin-By-Zaron-Acne-Control-Glow-Wash.webp', NULL, NULL),
('PROD-020', 'CAT-06', 'Cleansers', 'Good Molecules Hydrating Facial Cleansing Gel 200ml', 'Good Molecules', 'Cleanser', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Good-Molecules-Hydrating-Facial-Cleansing-Gel-200Ml.webp', NULL, NULL),
('PROD-023', 'CAT-06', 'Cleansers', 'Good Molecules Brightening & Dark Spots Bar 85g', 'Good Molecules', 'Cleanser', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/690EB7EF-E4DF-4812-ADE0-E2A085B22A6C.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/7530AB32-3357-4082-980C-644B8EFCEBB5.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/690EB7EF-E4DF-4812-ADE0-E2A085B22A6C.jpeg'),
('PROD-033', 'CAT-06', 'Cleansers', 'Cosrx Salicylic Gentle Cleanser', 'Cosrx', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Cosrx-Salicylic-Gentle-Cleanser-50ML.jpg', NULL, NULL),
('PROD-034', 'CAT-06', 'Cleansers', 'Cosrx Low pH Gel Cleanser 150ml', 'Cosrx', 'Cleanser', 'Sensitive', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Low-Ph-Gel-Cleanser-150Ml.jpg', NULL, NULL),
('PROD-048', 'CAT-06', 'Cleansers', 'Beauty Of Joseon Cleansing Oil 210ml', 'Beauty Of Joseon', 'Cleanser', 'All skin', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Beauty-Of-Joseon-Cleansing-Oil-210Ml.jpg', NULL, NULL),
('PROD-049', 'CAT-06', 'Cleansers', 'Beauty Of Joseon Radiance Cleansing Balm 100ml', 'Beauty Of Joseon', 'Cleanser', 'All skin', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Beauty-Of-Joseon-Radiance-Cleansing-Balm-100Ml.jpg', NULL, NULL),
('PROD-064', 'CAT-06', 'Cleansers', 'Anua Heartleaf Pore Control Cleansing Oil 200ml', 'Anua', 'Cleanser', 'Pores', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/anua-cleansing-oil.jpg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/anua-cleansing-oil.jpg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/51JS2lgk5FL._SL1080_.jpg'),
('PROD-065', 'CAT-06', 'Cleansers', 'Anua Heartleaf LHA Moisture Peeling Gel 120ml', 'Anua', 'Cleanser', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/41zTfqwVqJL._SL1000_.jpg', NULL, NULL),
('PROD-072', 'CAT-06', 'Cleansers', 'Heimish All Clean Balm', 'Heimish', 'Cleanser', 'All skin', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Heimish-All-Clean-Balm.jpg', NULL, NULL),
('PROD-080', 'CAT-06', 'Cleansers', 'Topicals Faded Brightening Cleansing Bar', 'Topicals', 'Cleanser', 'PIH/Dark spots', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Faded-Topicals-Brightening-And-Clearing-Serum-50Ml.jpg', NULL, NULL),
('PROD-092', 'CAT-06', 'Cleansers', 'Medix Vitamin C + Niacinamide Body Wash', 'Medix 5.5', 'Body Wash', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/WhatsApp-Image-2025-05-31-at-17.10.26.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/MDX31_Vit_C-Body_Wash_Slide_2_Key_Ingredients_NO_LOGO_040125.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/WhatsApp-Image-2025-05-31-at-17.10.26-1.jpeg'),
('PROD-097', 'CAT-06', 'Cleansers', 'Nip + Fab Vitamin C Fix Cleanser', 'Nip + Fab', 'Cleanser', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/D1E45FD9-6C99-4CBB-9AB4-3D28717C8E3B.jpeg', NULL, NULL),
('PROD-098', 'CAT-06', 'Cleansers', 'Naturium Vitamin C Complex Face Cleanser 210ml', 'Naturium', 'Cleanser', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Naturium-Vit-C-Complex-Cleanser-210.webp', NULL, NULL),
('PROD-108', 'CAT-06', 'Cleansers', 'Panoxyl Acne Foaming Wash 10% Benzoyl Peroxide 170g', 'Panoxyl', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Panoxyl-Acne-Creamy-Wash-10-Benzoyl-Peroxide-170G.jpg', NULL, NULL),
('PROD-109', 'CAT-06', 'Cleansers', 'Panoxyl Acne Creamy Wash 4% Benzoyl Peroxide 170g', 'Panoxyl', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Panoxyl-Acne-Creamy-Wash-4-Benzoyl-Peroxide-170G.jpg', NULL, NULL),
('PROD-111', 'CAT-06', 'Cleansers', 'Panoxyl Acne Treatment Bar 113g', 'Panoxyl', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Panoxyl-acne-treatment-BAR-113g.webp', NULL, NULL),
('PROD-116', 'CAT-06', 'Cleansers', 'La Roche-Posay Effaclar Dual Acne Face Wash 4% Benzoyl Peroxide', 'La Roche-Posay', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-22-at-14.22.40.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-22-at-14.22.40-2.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-22-at-14.22.40-1.jpeg'),
('PROD-117', 'CAT-06', 'Cleansers', 'La Roche-Posay Lipikar AP+ Gentle Foaming Moisturizing Wash', 'La Roche-Posay', 'Cleanser', 'Dry/Eczema', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-22-at-14.31.16-3.jpeg', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-22-at-14.31.16-2.jpeg'),
('PROD-118', 'CAT-06', 'Cleansers', 'Cerave Renewing SA Cleanser', 'CeraVe', 'Cleanser', 'Texture', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2815.webp', NULL, NULL),
('PROD-119', 'CAT-06', 'Cleansers', 'Cerave Foaming Facial Cleanser', 'CeraVe', 'Cleanser', 'Oily/Combo', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2817.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2818.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2819.jpeg'),
('PROD-120', 'CAT-06', 'Cleansers', 'Cerave Hydrating Facial Cleanser', 'CeraVe', 'Cleanser', 'Dry/Sensitive', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2820.webp', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2821.webp'),
('PROD-121', 'CAT-06', 'Cleansers', 'Cerave Acne Foaming Cream Cleanser', 'CeraVe', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2817.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2818.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_2819.jpeg'),
('PROD-123', 'CAT-06', 'Cleansers', 'Neutrogena Oil Free Acne Wash Pink Grapefruit Foaming Scrub', 'Neutrogena', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/01/IMG_1005-scaled.webp', NULL, NULL),
('PROD-124', 'CAT-06', 'Cleansers', 'Neutrogena Oil Free Acne Wash Pink Grapefruit Facial Cleanser', 'Neutrogena', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/01/IMG_0917.jpeg', NULL, NULL),
('PROD-125', 'CAT-06', 'Cleansers', 'Neutrogena Oil Free Acne Wash with Salicylic Acid Fragrance Free', 'Neutrogena', 'Cleanser', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/01/IMG_0916.jpeg', NULL, NULL),
('PROD-135', 'CAT-06', 'Cleansers', 'Tiam Snail & Azulene Low pH Cleanser', 'Tiam', 'Cleanser', 'Soothing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1902.jpeg', NULL, NULL),
('PROD-147', 'CAT-06', 'Cleansers', 'Heimish All Clean Balm (additional)', 'Heimish', 'Cleanser', 'All skin', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Heimish-All-Clean-Balm.jpg', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id, category_name = EXCLUDED.category_name,
  product_name = EXCLUDED.product_name, brand = EXCLUDED.brand, sub_type = EXCLUDED.sub_type,
  finish = EXCLUDED.finish, best_for = EXCLUDED.best_for, confidence_level = EXCLUDED.confidence_level,
  skin_concern_tags = EXCLUDED.skin_concern_tags, image_url = EXCLUDED.image_url,
  image_url_2 = EXCLUDED.image_url_2, image_url_3 = EXCLUDED.image_url_3;

-- ==========================================
-- Toners (CAT-16)
-- ==========================================
INSERT INTO public.products (id, category_id, category_name, product_name, brand, sub_type, finish, best_for, confidence_level, skin_concern_tags, image_url, image_url_2, image_url_3) VALUES
('PROD-003', 'CAT-16', 'Toner', 'Skin By Zaron Brightening Toner', 'Skin By Zaron', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/main-product-50-1725059610365.webp', NULL, NULL),
('PROD-011', 'CAT-16', 'Toner', 'Skin By Zaron 2% Salicylic Acid Toner', 'Skin By Zaron', 'Toner', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/main-product-267-1725059804509.webp', NULL, NULL),
('PROD-017', 'CAT-16', 'Toner', 'Good Molecules Niacinamide Brightening Toner', 'Good Molecules', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Niacinamide-Brightening-Toner-30Ml.webp', NULL, NULL),
('PROD-024', 'CAT-16', 'Toner', 'Good Molecules Glycolic Exfoliating Toner 120ml', 'Good Molecules', 'Toner', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Good-Molecules-Glycolic-Exfoliating-Toner-120ml.webp', NULL, NULL),
('PROD-028', 'CAT-16', 'Toner', 'Cosrx Propolis Synergy Toner 150ml', 'Cosrx', 'Toner', 'Soothing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Propolis-Synergy-Toner-150Ml.jpg', NULL, NULL),
('PROD-036', 'CAT-16', 'Toner', 'Cosrx AHA/BHA Clarifying Treatment Toner 150ml', 'Cosrx', 'Toner', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/cosrx-aha-bha-clarifying-treatment-toner-150ml-644.jpg', NULL, NULL),
('PROD-040', 'CAT-16', 'Toner', 'Isntree Hyaluronic Acid Toner', 'Isntree', 'Toner', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Isntree-Hyaluronic-Acid-Toner.webp', NULL, NULL),
('PROD-041', 'CAT-16', 'Toner', 'Isntree Hyaluronic Acid Toner Plus', 'Isntree', 'Toner', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Isntree-Hyaluronic-Acid-Toner-Plus.jpg', NULL, NULL),
('PROD-042', 'CAT-16', 'Toner', 'Isntree Green Tea Fresh Toner', 'Isntree', 'Toner', 'Soothing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Isntree-Green-Tea-Fresh-Toner.webp', NULL, NULL),
('PROD-058', 'CAT-16', 'Toner', 'The Ordinary Glycolic Acid Toner 240ml', 'The Ordinary', 'Toner', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/The-Ordinary-Glycolic-Acid-100Ml.webp', NULL, NULL),
('PROD-061', 'CAT-16', 'Toner', 'Anua Heartleaf 77% Soothing Toner 250ml', 'Anua', 'Toner', 'Soothing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Anua-Heartleaf-77-Soothing-Toner-250ml.webp', NULL, NULL),
('PROD-066', 'CAT-16', 'Toner', 'Anua BHA 2% Gentle Exfoliating Toner 150ml', 'Anua', 'Toner', 'Acne/Pores', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/41-YpT9x1zL._AC_SL1000_.jpg', NULL, NULL),
('PROD-085', 'CAT-16', 'Toner', 'Advanced Clinicals Vitamin C Glow Facial Mist Toner', 'Advanced Clinicals', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/61hWvsTXqBL._AC_SL1500_.jpg', NULL, NULL),
('PROD-086', 'CAT-16', 'Toner', 'Advanced Clinicals Vitamin C Face Toner w/Ferulic Acid & Rosewater', 'Advanced Clinicals', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/81-eXZo212L._AC_SL1500_.jpg', NULL, NULL),
('PROD-132', 'CAT-16', 'Toner', 'Tiam Vita B3 Mist Toner 200ml', 'Tiam', 'Toner', 'Niacinamide', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/02/6654.webp', NULL, NULL),
('PROD-133', 'CAT-16', 'Toner', 'Tiam Vita B5 Toner', 'Tiam', 'Toner', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/Tiam-b5-toner.webp', NULL, NULL),
('PROD-136', 'CAT-16', 'Toner', 'Tiam AC Fighting AHA BHA PHA Toner', 'Tiam', 'Toner', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/1EB1BC9C-B7E7-48BB-8C93-D0841FC9CB0D.jpeg', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/B0C50021-1E5E-45F1-BCD1-061844112869.jpeg'),
('PROD-138', 'CAT-16', 'Toner', 'Acwell 5.5 Licorice pH Balancing Cleansing Toner', 'Acwell', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/FF211E21-8763-4C6A-8D2B-816F1323091F.jpeg', NULL, NULL),
('PROD-139', 'CAT-16', 'Toner', 'Skin1004 Madagascar Centella Tone Brightening Boosting Toner', 'Skin1004', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/09/skin1004-toner-210ml-tone-brightening-boosting-toner-38642937135350_1440x.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/09/skin1004-toner-210ml-madagascar-centella-tone-brightening-boosting-toner-36440310350070_1440x.webp', NULL),
('PROD-141', 'CAT-16', 'Toner', 'Missha Vita C Plus Brightening Toner 200ml', 'Missha', 'Toner', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/10/15C891E3-D1AB-4B20-AD80-1EAFEFEBBE71.webp', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id, category_name = EXCLUDED.category_name,
  product_name = EXCLUDED.product_name, brand = EXCLUDED.brand, sub_type = EXCLUDED.sub_type,
  finish = EXCLUDED.finish, best_for = EXCLUDED.best_for, confidence_level = EXCLUDED.confidence_level,
  skin_concern_tags = EXCLUDED.skin_concern_tags, image_url = EXCLUDED.image_url,
  image_url_2 = EXCLUDED.image_url_2, image_url_3 = EXCLUDED.image_url_3;

-- ==========================================
-- Serums (CAT-14)
-- ==========================================
INSERT INTO public.products (id, category_id, category_name, product_name, brand, sub_type, finish, best_for, confidence_level, skin_concern_tags, image_url, image_url_2, image_url_3) VALUES
('PROD-004', 'CAT-14', 'Serum', 'Skin By Zaron Retinol Serum', 'Skin By Zaron', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Skin-By-Zaron-Retinol-Serum.jpg', NULL, NULL),
('PROD-005', 'CAT-14', 'Serum', 'Skin By Zaron Vitamin C Serum', 'Skin By Zaron', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Skin-By-Zaron-Vitamin-Serum.jpg', NULL, NULL),
('PROD-009', 'CAT-14', 'Serum', 'Skin By Zaron 2% Alpha-Arbutin Serum', 'Skin By Zaron', 'Serum', 'Brightening/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/main-product-55-1725059731924.webp', NULL, NULL),
('PROD-012', 'CAT-14', 'Serum', 'Zaron Slain Regenerating Hydrating Serum', 'Skin By Zaron', 'Serum', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Zaron-Slain-Regenerating-Hydrating-Serum.jpg', NULL, NULL),
('PROD-013', 'CAT-14', 'Serum', 'Good Molecules Daily Brightening Serum 30ml', 'Good Molecules', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Daily-Brightening-Serum-30Ml.jpg', NULL, NULL),
('PROD-014', 'CAT-14', 'Serum', 'Good Molecules Niacinamide Serum 30ml', 'Good Molecules', 'Serum', 'Oiliness/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Niacinamide-Serum-30Ml.jpg', NULL, NULL),
('PROD-018', 'CAT-14', 'Serum', 'Good Molecules Discoloration Serum 30ml', 'Good Molecules', 'Serum', 'PIH/Dark spots', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Discoloration-Serum-30Ml.jpg', NULL, NULL),
('PROD-019', 'CAT-14', 'Serum', 'Good Molecules Discoloration Serum 75ml', 'Good Molecules', 'Serum', 'PIH/Dark spots', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Good-Molecules-Discoloration-Serum-75Ml.webp', NULL, NULL),
('PROD-025', 'CAT-14', 'Serum', 'Good Molecules Super Peptides Serum 30ml', 'Good Molecules', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Good-Molecules-Super-peptides-Serum-30ml.webp', NULL, NULL),
('PROD-026', 'CAT-14', 'Serum', 'Good Molecules Vitamin C Serum with Oryzanol 30ml', 'Good Molecules', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Good-Molecules-Vitamin-C-serum-with-oryzanol-30ml.webp', NULL, NULL),
('PROD-039', 'CAT-14', 'Serum', 'Cosrx The 6 Peptide Skin Booster', 'Cosrx', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1957.jpeg', NULL, NULL),
('PROD-046', 'CAT-14', 'Serum', 'Axis-Y Dark Spot Correcting Serum', 'Axis-Y', 'Serum', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Axis-Y-Dark-Spot-Correcting-Serum.jpg', NULL, NULL),
('PROD-047', 'CAT-14', 'Serum', 'Beauty Of Joseon Glow Serum 30ml', 'Beauty Of Joseon', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Beauty-Of-Joseon-Glow-Serum-30Ml.webp', NULL, NULL),
('PROD-050', 'CAT-14', 'Serum', 'Beauty Of Joseon Glow Deep Serum 30ml', 'Beauty Of Joseon', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Beauty-Of-Joseon-Glow-Deep-Serum-30Ml.jpg', NULL, NULL),
('PROD-054', 'CAT-14', 'Serum', 'The Ordinary Caffeine Solution 30ml', 'The Ordinary', 'Serum', 'Eye Serum', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/The-Ordinary-Caffine-Solution-30Ml-1.jpg', NULL, NULL),
('PROD-055', 'CAT-14', 'Serum', 'The Ordinary Alpha Arbutin 30ml', 'The Ordinary', 'Serum', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/FY25-D41247-ORD-Web-Alp-Arb-2pct-30ml-1x1-EN-1.webp', NULL, NULL),
('PROD-057', 'CAT-14', 'Serum', 'The Ordinary Retinol Serum 30ml', 'The Ordinary', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/The-Ordinary-Retinol-Serum-30Ml.jpg', NULL, NULL),
('PROD-059', 'CAT-14', 'Serum', 'The Ordinary Multi Peptide Eye Serum 15ml', 'The Ordinary', 'Serum', 'Eye Serum', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/The-Ordinary-Multi-Peptide-Eye-Serum-15Ml.jpg', NULL, NULL),
('PROD-060', 'CAT-14', 'Serum', 'The Ordinary Retinol Serum 0.5% 30ml', 'The Ordinary', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/The-Ordinary-Retinol-Serum-1-30Ml.avif', NULL, NULL),
('PROD-063', 'CAT-14', 'Serum', 'Anua Niacinamide 10% x TXA 4% 30ml', 'Anua', 'Serum', 'PIH/Oiliness', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Anua-Niacinamide-10-x-TXA-4-30ml.webp', NULL, NULL),
('PROD-067', 'CAT-14', 'Serum', 'Anua Peach 70 Niacinamide Serum 30ml', 'Anua', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/41UsAM1r9bL._SL1000_.jpg', NULL, NULL),
('PROD-068', 'CAT-14', 'Serum', 'Anua Azelaic Acid 10 Hyaluron', 'Anua', 'Serum', 'Acne/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/IMG_1657.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/IMG_1660.jpeg', NULL),
('PROD-070', 'CAT-14', 'Serum', 'Some By Mi Miracle Serum 50ml', 'Some By Mi', 'Serum', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Some-By-Mi-Miracle-Serum-50Ml.webp', NULL, NULL),
('PROD-077', 'CAT-14', 'Serum', 'Topicals Faded Brightening and Clearing Serum', 'Topicals', 'Serum', 'PIH/Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Faded-Topicals-Brightening-And-Clearing-Serum-50Ml.jpg', NULL, NULL),
('PROD-081', 'CAT-14', 'Serum', 'Timeless Vitamin C Serum 20%', 'Timeless', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Timeless-Vitamin-C-Serum-20.jpg', NULL, NULL),
('PROD-082', 'CAT-14', 'Serum', 'Timeless Skin Care Vitamin C Serum with Vitamin E & Ferulic Acid', 'Timeless', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/10/A6A1C497-1A23-4A1A-8CC2-57008E98939C.jpeg', NULL, NULL),
('PROD-083', 'CAT-14', 'Serum', 'Advanced Clinicals Vitamin C Face Serum 1.75oz', 'Advanced Clinicals', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Advanced-Clinicals-1.75Oz-Vitamin-C-Serum.webp', NULL, NULL),
('PROD-090', 'CAT-14', 'Serum', 'Medix 5.5 Vitamin C Serum', 'Medix 5.5', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Medix-5.5-Vitamin-C-Serum.jpg', NULL, NULL),
('PROD-094', 'CAT-14', 'Serum', 'Balance Active Vitamin C Serum 30ml', 'Balance Active', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Balance-Active-Vitamin-C-Serum-30Ml.webp', NULL, NULL),
('PROD-095', 'CAT-14', 'Serum', 'Nip + Fab Vitamin C Fix Serum 5%', 'Nip + Fab', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Nip-Fab-illuminate-Vitamin-C-Fix-Serum-1.webp', NULL, NULL),
('PROD-099', 'CAT-14', 'Serum', 'Naturium Vitamin C Complex Face Serum 30ml', 'Naturium', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Naturium-Vit-C-Complex-Serum-30Ml.webp', NULL, NULL),
('PROD-100', 'CAT-14', 'Serum', 'Naturium Tranexamic Topical Acid 5% 30ml', 'Naturium', 'Serum', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Naturium-Tranexamic-Topical-Acid-5-30ml.webp', NULL, NULL),
('PROD-101', 'CAT-14', 'Serum', 'Naturium Multi Bright Tranexamic Acid Treatment 5% 30ml', 'Naturium', 'Serum', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Naturium-Multi-Tranexamic-Acid-Treatment-5-30ml.webp', NULL, NULL),
('PROD-103', 'CAT-14', 'Serum', 'Naturium Alpha Arbutin Serum 2% 30ml', 'Naturium', 'Serum', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/02/UK200036497_NATURIUM_3.jpg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/02/UK200036497_NATURIUM.jpg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/02/UK200036497_NATURIUM_1.jpg'),
('PROD-104', 'CAT-14', 'Serum', 'Naturium Azelaic Topical Acid 10% 30ml', 'Naturium', 'Serum', 'Acne/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/Naturium_Azaleic_Acid_Front_CapOn_Bone_1_700x.webp', NULL, NULL),
('PROD-105', 'CAT-14', 'Serum', 'Naturium Mandelic Topical Acid 12% 30ml', 'Naturium', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/Naturium_Mandelic_Acid_Front_CapOn_Bone_1_700x.webp', NULL, NULL),
('PROD-122', 'CAT-14', 'Serum', 'Cerave Resurfacing Retinol Serum', 'CeraVe', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_3055.webp', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_3056.webp'),
('PROD-131', 'CAT-14', 'Serum', 'Tiam Vita B3 Source 40ml', 'Tiam', 'Serum', 'Niacinamide/Oiliness', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/tiam-vita-b3-new.jpg', NULL, NULL),
('PROD-137', 'CAT-14', 'Serum', 'Acwell 5.5 Licorice pH Balancing Advance Serum', 'Acwell', 'Serum', 'PIH/Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Acwell-5.5-Licorice-Ph-Balancing-Advance-Serum.webp', NULL, NULL),
('PROD-140', 'CAT-14', 'Serum', 'Skin1004 Madagascar Centella Tone Brightening Ampoule', 'Skin1004', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1667.webp', NULL, NULL),
('PROD-144', 'CAT-14', 'Serum', 'Dr Althea Gentle Vitamin C Serum', 'Dr Althea', 'Serum', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/dr-althea-gentlevitamincserum.webp', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/dr-althea-vit-c-20.webp'),
('PROD-145', 'CAT-14', 'Serum', 'Jumiso Brightening & Balancing Facial Serum', 'Jumiso', 'Serum', 'PIH/Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/IMG_1666.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/IMG_1664.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/05/IMG_1665.webp'),
('PROD-146', 'CAT-14', 'Serum', 'Haruharu Wonder Black Rice Hyaluronic Anti-Wrinkle Serum 50ml', 'Haruharu Wonder', 'Serum', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Haruharu-Wonder-Black-Rice-Hyaluronic-Anti-Wrinkle-Serum-50Ml.webp', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id, category_name = EXCLUDED.category_name,
  product_name = EXCLUDED.product_name, brand = EXCLUDED.brand, sub_type = EXCLUDED.sub_type,
  finish = EXCLUDED.finish, best_for = EXCLUDED.best_for, confidence_level = EXCLUDED.confidence_level,
  skin_concern_tags = EXCLUDED.skin_concern_tags, image_url = EXCLUDED.image_url,
  image_url_2 = EXCLUDED.image_url_2, image_url_3 = EXCLUDED.image_url_3;

-- ==========================================
-- Moisturizers (CAT-12)
-- ==========================================
INSERT INTO public.products (id, category_id, category_name, product_name, brand, sub_type, finish, best_for, confidence_level, skin_concern_tags, image_url, image_url_2, image_url_3) VALUES
('PROD-008', 'CAT-12', 'Moisturizer', 'Skin By Zaron Vitamin C Face Cream', 'Skin By Zaron', 'Face cream', 'Brightening', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/1733748427.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/1733746622.webp', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/1733748427.webp'),
('PROD-021', 'CAT-12', 'Moisturizer', 'Good Molecules Lightweight Daily Moisturizer 100ml', 'Good Molecules', 'Moisturizer', 'All skin', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Good-Molecules-Light-Weight-Daily-Moisturizer-100Ml.webp', NULL, NULL),
('PROD-022', 'CAT-12', 'Moisturizer', 'Good Molecules Yerba Mate Wake Up Eye Gel 15ml', 'Good Molecules', 'Eye Gel', 'Eyes puffiness', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Good-Molecules-Yerba-Mate-Wake-Up-Eye-Gel-15Ml.jpg', NULL, NULL),
('PROD-031', 'CAT-12', 'Moisturizer', 'Cosrx Snail 92 All-in-One Cream 100g', 'Cosrx', 'Moisturizer', 'Repair', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Snail-92-All-In-One-Cream-100G.jpg', NULL, NULL),
('PROD-035', 'CAT-12', 'Moisturizer', 'Cosrx Oil-Free Moisturizer 100ml', 'Cosrx', 'Moisturizer', 'Oily/Combo', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Oil-Free-Moisturizer-100Ml.jpg', NULL, NULL),
('PROD-038', 'CAT-12', 'Moisturizer', 'Cosrx Advanced Snail 92 All-in-One Cream Tube 100g', 'Cosrx', 'Moisturizer', 'Repair', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/10/5B0251FB-BD36-461D-AA0C-F8E6ADC16ACA.webp', NULL, NULL),
('PROD-043', 'CAT-12', 'Moisturizer', 'Isntree Fresh Emulsion', 'Isntree', 'Moisturizer', 'Hydrating', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Isntree-Fresh-Emulsion.webp', NULL, NULL),
('PROD-044', 'CAT-12', 'Moisturizer', 'Isntree Hyaluronic Acid Moist Cream', 'Isntree', 'Moisturizer', 'Hydrating', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/03/IMG_1942.jpeg', NULL, NULL),
('PROD-051', 'CAT-12', 'Moisturizer', 'Beauty Of Joseon Dynasty Face Cream Moisturizer', 'Beauty Of Joseon', 'Face cream', 'Hydrating', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/BEAUTY-OF-JOSEON-DYNASTY-FACE-CREAM-MOISTURIZER.jpg', NULL, NULL),
('PROD-062', 'CAT-12', 'Moisturizer', 'Anua Heartleaf 70 Intense Calming Cream 50ml', 'Anua', 'Moisturizer', 'Soothing', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Anua-Heartleaf-70-intense-Calming-Cream-50ml.webp', NULL, NULL),
('PROD-069', 'CAT-12', 'Moisturizer', 'Some By Mi Miracle Cream', 'Some By Mi', 'Moisturizer', 'Acne', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Some-By-Mi-Miracle-Cream.webp', NULL, NULL),
('PROD-071', 'CAT-12', 'Moisturizer', 'Heimish Marine Care Face Oil', 'Heimish', 'Face Oil', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Heimish-Marine-Care-Face-Oil.jpg', NULL, NULL),
('PROD-073', 'CAT-12', 'Moisturizer', 'Msmetics Moisture Bomb 50ml', 'Msmetics', 'Moisturizer', 'Hydrating', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Msmetics-Moisture-Bomb-50Ml.webp', NULL, NULL),
('PROD-074', 'CAT-12', 'Moisturizer', 'Msmetics Moisture Potion 50ml', 'Msmetics', 'Moisturizer', 'Hydrating', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Msmetics-Moisture-Potion-50Ml.webp', NULL, NULL),
('PROD-084', 'CAT-12', 'Moisturizer', 'Advanced Clinicals Vitamin C Brightening Gel Cream 2oz', 'Advanced Clinicals', 'Moisturizer', 'Brightening', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Advanced-Clinicals-2Oz-Vitamin-C-Face-Brightening-Gel-Cream.jpg', NULL, NULL),
('PROD-088', 'CAT-12', 'Moisturizer', 'Advanced Clinicals Dark Spot Brightening Face Moisturizer Lotion', 'Advanced Clinicals', 'Face Cream', 'PIH', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/81ZCXGWw-VL._SL1500_.jpg', NULL, NULL),
('PROD-089', 'CAT-12', 'Moisturizer', 'Medix 5.5 Vitamin C Cream 15floz', 'Medix 5.5', 'Moisturizer', 'Brightening', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/94DC0B42-003B-4835-9444-F86E122F3C71.jpeg', NULL, NULL),
('PROD-093', 'CAT-12', 'Moisturizer', 'Medi-Peel Vitamin C Lotion', 'Medi-Peel', 'Body Lotion', 'Brightening', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Medi-Peel-Vitamin-C-Lotion.jpg', NULL, NULL),
('PROD-096', 'CAT-12', 'Moisturizer', 'Nip + Fab Retinol Fix Overnight Cream 50ml', 'Nip + Fab', 'Moisturizer', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/63C47D94-E559-4BC8-8AD3-E4E3B949C7FC.png', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/8E9DD605-8C85-4C89-AA5D-F0585A537000.png'),
('PROD-106', 'CAT-12', 'Moisturizer', 'Naturium Barrier Bounce 50ml', 'Naturium', 'Moisturizer', 'Barrier repair', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/96DAFD88-6100-436D-BC41-E1323EE27A28.jpeg', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/CC40ED31-5D2D-4935-8E0B-13CA11692055.jpeg'),
('PROD-110', 'CAT-12', 'Moisturizer', 'Panoxyl Balancing Repair Moisturizer with Niacinamide 85g', 'Panoxyl', 'Moisturizer', 'Acne', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Panoxyl-balancing-repair-moisturizer-with-niacinamide-85g.webp', NULL, NULL),
('PROD-134', 'CAT-12', 'Moisturizer', 'Tiam Alpha-5 Mela Care Cream', 'Tiam', 'Moisturizer', 'PIH', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1901.webp', NULL, NULL),
('PROD-143', 'CAT-12', 'Moisturizer', 'Dr Althea 345 Relief Cream', 'Dr Althea', 'Moisturizer', 'Soothing', 'Serums, toners, cleansers, Moisturizers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1947.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1946.jpeg', NULL)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id, category_name = EXCLUDED.category_name,
  product_name = EXCLUDED.product_name, brand = EXCLUDED.brand, sub_type = EXCLUDED.sub_type,
  finish = EXCLUDED.finish, best_for = EXCLUDED.best_for, confidence_level = EXCLUDED.confidence_level,
  skin_concern_tags = EXCLUDED.skin_concern_tags, image_url = EXCLUDED.image_url,
  image_url_2 = EXCLUDED.image_url_2, image_url_3 = EXCLUDED.image_url_3;

-- ==========================================
-- Other Categories
-- ==========================================
INSERT INTO public.products (id, category_id, category_name, product_name, brand, sub_type, finish, best_for, confidence_level, skin_concern_tags, image_url, image_url_2, image_url_3) VALUES
-- Exfoliants (CAT-08)
('PROD-010', 'CAT-08', 'Exfoliant', 'Skin By Zaron 7% Glycolic Acid', 'Skin By Zaron', 'Exfoliant', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/main-product-266-1725059746055.webp', NULL, 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2025/08/alt-product-266-1725059748261.webp'),
('PROD-032', 'CAT-08', 'Exfoliant', 'Cosrx BHA Blackhead Power Liquid 100ml', 'Cosrx', 'Exfoliant', 'Acne/Pores', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Bha-Black-Head-Power-Liquid-100Ml.webp', NULL, NULL),
('PROD-056', 'CAT-08', 'Exfoliant', 'The Ordinary Lactic Acid', 'The Ordinary', 'Exfoliant', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/51fzAcW78WL._SL1500_.jpg', NULL, NULL),
('PROD-102', 'CAT-08', 'Exfoliant', 'Naturium BHA Liquid Exfoliant 2%', 'Naturium', 'Exfoliant', 'Acne/Pores', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Naturium-BHA-Liquid-Exfoliant-2.jpg', NULL, NULL),
('PROD-113', 'CAT-08', 'Exfoliant', 'Panoxyl Clarifying Exfoliant 2% Salicylic Acid 118g', 'Panoxyl', 'Exfoliant', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Panoxyl-Clarifying-exfoliant-2-salicylic-acid-118g.jpg', NULL, NULL),
-- Essences (CAT-07)
('PROD-029', 'CAT-07', 'Essence', 'Cosrx Dual Essence', 'Cosrx', 'Essence', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Dual-Essence.jpg', NULL, NULL),
('PROD-030', 'CAT-07', 'Essence', 'Cosrx Snail Mucin Essence 100ml', 'Cosrx', 'Essence', 'Repair/Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Cosrx-Snail-Mucin-Essence-100Ml.jpg', NULL, NULL),
('PROD-052', 'CAT-07', 'Essence', 'Hadalabo Premium Gold 170ml', 'Hadalabo', 'Toner', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Hadalabo-Premium-Gold-170Ml.jpg', NULL, NULL),
('PROD-053', 'CAT-07', 'Essence', 'Hadalabo Premium Blue 170ml', 'Hadalabo', 'Toner', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Hadalabo-Premium-Blue-170Ml.jpg', NULL, NULL),
('PROD-130', 'CAT-07', 'Essence', 'Tiam Snail Azulence Water Essence 180ml', 'Tiam', 'Essence', 'Soothing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Tiam-Snail-Azulence-Water-Essence-180Ml.jpg', NULL, NULL),
-- Treatments (CAT-17)
('PROD-015', 'CAT-17', 'Treatment', 'Good Molecules Overnight Treatment 30ml', 'Good Molecules', 'Treatment', 'Repair', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Overnight-Treatment-30Ml.jpg', NULL, NULL),
('PROD-045', 'CAT-17', 'Treatment', 'Axis-Y Spot the Difference Blemish Treatment', 'Axis-Y', 'Treatment', 'Acne/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Axis-Y-Blemish-Treatment.webp', NULL, NULL),
('PROD-079', 'CAT-17', 'Treatment', 'Topicals High Roller Ingrown Hair Serum Roll-on 50ml', 'Topicals', 'Treatment', 'Ingrown hair', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/716eYR4n-qL._SL1500_.jpg', NULL, NULL),
('PROD-112', 'CAT-17', 'Treatment', 'Panoxyl Adapalene Gel USP 0.1% 15g', 'Panoxyl', 'Treatment', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/Panoxyl-Adapalene-gel-usp-0.1-acne-treatment.webp', NULL, NULL),
('PROD-126', 'CAT-17', 'Treatment', 'Zapzyt Acne Treatment Gel', 'Zapzyt', 'Treatment', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/10/275F130E-5DC0-478A-BACA-CDB1306ABF76.jpeg', NULL, NULL),
('PROD-127', 'CAT-17', 'Treatment', 'Touch Acne Treatment Gel', 'Touch', 'Treatment', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Touch-Acne-Treatment-Gel.jpg', NULL, NULL),
('PROD-128', 'CAT-17', 'Treatment', 'Touch Bright and Clear Cream 2oz', 'Touch', 'Treatment', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Touch-Bright-And-Clear-Cream-2-Oz-56.7.webp', NULL, NULL),
('PROD-129', 'CAT-17', 'Treatment', 'Touch Ingrown Hair Roll-On', 'Touch', 'Treatment', 'Ingrown hair', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Touch-Ingrown-Hair-Roll-On.webp', NULL, NULL),
('PROD-148', 'CAT-17', 'Treatment', 'Ezanic Azelaic Acid Gel 20% 15g', 'Ezanic', 'Treatment', 'Acne/PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/05/Ezanic-Azelaic-Acid-Gel.jpg', NULL, NULL),
('PROD-149', 'CAT-17', 'Treatment', 'Kojivit Ultra Gel 30g', 'Kojivit', 'Treatment', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/08/kojivit-Ultra-gel-30g.webp', NULL, NULL),
-- Anti-Aging (CAT-01)
('PROD-016', 'CAT-01', 'Anti-Aging', 'Good Molecules Gentle Retinol Cream 30ml', 'Good Molecules', 'Anti-Aging', 'Moisturizer', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Good-Molecules-Gentle-Retinol-Cream-30G.webp', NULL, NULL),
('PROD-087', 'CAT-01', 'Anti-Aging', 'Advanced Clinicals 5-in-1 Multi Correction Anti-Ageing Eye Serum', 'Advanced Clinicals', 'Anti-Aging', 'Serum', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/710HqR5DfSL._SL1500_.jpg', NULL, NULL),
('PROD-091', 'CAT-01', 'Anti-Aging', 'Medix 5.5 Retinol Cream 15floz', 'Medix 5.5', 'Anti-Aging', 'Moisturizer', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Medix-5.5-Retinol-Cream-15Floz-144Ml.webp', NULL, NULL),
-- Eye Masks (CAT-09)
('PROD-027', 'CAT-09', 'Eye Mask', 'Good Molecules Caffeine Energizing Hydrogel Eye Patches', 'Good Molecules', 'Eye Patches', 'Eyes puffiness', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/01/IMG_0921.jpeg', NULL, NULL),
('PROD-078', 'CAT-09', 'Eye Mask', 'Topicals Faded Under Eye Masks', 'Topicals', 'Eye Mask', 'PIH', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/240623_TOPICALS_Faded_Eye_Ppage_Image_6_6_11zon_750x.webp', NULL, NULL),
-- Masks (CAT-11)
('PROD-075', 'CAT-11', 'Mask', 'Dr Jart Hyaluronic Face Mask', 'Dr Jart', 'Mask', 'Hydrating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Dr-Jart-Hyaluronic-Face-Mask.avif', NULL, NULL),
('PROD-076', 'CAT-11', 'Mask', 'Dr Jart Vitamin C Face Mask', 'Dr Jart', 'Mask', 'Brightening', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/04/Dr-Jart-Vitamin-C-Face-Mask.avif', NULL, NULL),
('PROD-107', 'CAT-11', 'Mask', 'Naturium AHA Exfoliating Mask 10%', 'Naturium', 'Exfoliant', 'Exfoliating', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/141CD9ED-ED6D-4B80-AB70-4C49A3AEE129.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/11/660120DA-D752-4114-9B52-D3A9286E169C.jpeg', NULL),
-- Patches (CAT-13)
('PROD-037', 'CAT-13', 'Patch', 'Cosrx Acne Pimple Master Patch', 'Cosrx', 'Patch', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/09/cosrx-acne-pimple-master-patch-52.jpg', NULL, NULL),
('PROD-114', 'CAT-13', 'Patch', 'Panoxyl Blemish Aftercare Brightening Patches', 'Panoxyl', 'Patch', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1949.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1949-1.jpeg', 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1950.jpeg'),
('PROD-115', 'CAT-13', 'Patch', 'Panoxyl Overnight Spot Patches', 'Panoxyl', 'Patch', 'Acne', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2026/02/IMG_1952.jpeg', NULL, NULL),
-- Face Cream (CAT-10)
('PROD-142', 'CAT-10', 'Face Cream', 'Mary & May Tranexamic Eye Cream (Special Set, 2-pack)', 'Mary & May', 'Eye Cream', 'Anti-ageing', 'Serums, toners, cleansers, moisturisers, treatments for face', 'Medium', ARRAY['Acne','PIH','Dehydration','Ageing'], 'https://wholesalebeautyhub.co.uk/wp-content/uploads/2024/10/9CE7CA83-CCE4-40C6-AC6B-43C5B75BBA28.png', NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
  category_id = EXCLUDED.category_id, category_name = EXCLUDED.category_name,
  product_name = EXCLUDED.product_name, brand = EXCLUDED.brand, sub_type = EXCLUDED.sub_type,
  finish = EXCLUDED.finish, best_for = EXCLUDED.best_for, confidence_level = EXCLUDED.confidence_level,
  skin_concern_tags = EXCLUDED.skin_concern_tags, image_url = EXCLUDED.image_url,
  image_url_2 = EXCLUDED.image_url_2, image_url_3 = EXCLUDED.image_url_3;

-- Step 4: Update category product counts
UPDATE public.categories c SET product_count = (
  SELECT COUNT(*) FROM public.products p WHERE p.category_id = c.id
);

-- Step 5: Verify
SELECT category_name, COUNT(*) as total FROM public.products GROUP BY category_name ORDER BY total DESC;
