'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Mail, Lock, Eye, EyeOff, User, X, Loader2, Calendar, MapPin } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

function TermsModal({ onClose, tab }: { onClose: () => void; tab: 'terms' | 'privacy' }) {
  const [activeTab, setActiveTab] = useState(tab);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          <h2>{activeTab === 'terms' ? 'Terms of Service' : 'Privacy Policy'}</h2>
          <button className="modal-close" onClick={onClose}><X size={20} /></button>
        </div>
        <div className="modal-tabs">
          <button className={`modal-tab ${activeTab === 'terms' ? 'active' : ''}`} onClick={() => setActiveTab('terms')}>Terms of Service</button>
          <button className={`modal-tab ${activeTab === 'privacy' ? 'active' : ''}`} onClick={() => setActiveTab('privacy')}>Privacy Policy</button>
        </div>
        <div className="modal-body">
          {activeTab === 'terms' ? (
            <>
              <p className="modal-date">Last updated: March 13, 2026</p>
              <h3>1. Acceptance of Terms</h3>
              <p>By accessing or using WBH (&quot;the App&quot;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.</p>

              <h3>2. Description of Service</h3>
              <p>WBH provides AI-powered skin analysis and recommendations. Our service uses advanced machine learning to analyze skin conditions and provide educational insights. <strong>WBH is not a substitute for professional medical advice, diagnosis, or treatment.</strong></p>

              <h3>3. User Accounts</h3>
              <p>You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 16 years old to use WBH.</p>

              <h3>4. Acceptable Use</h3>
              <p>You agree not to misuse the service, attempt to reverse-engineer our AI models, or upload content that violates any laws. You may not use the App for commercial purposes without written consent.</p>

              <h3>5. AI Analysis Disclaimer</h3>
              <p>Skin analysis results are generated by AI and are for <strong>informational purposes only</strong>. Results should not be considered medical diagnoses. Always consult a qualified dermatologist for medical concerns. WBH is not liable for decisions made based on AI analysis results.</p>

              <h3>6. Consultations</h3>
              <p>Dermatologist consultations booked through the App are facilitated between you and independent healthcare professionals. WBH is not responsible for the advice or treatment provided by these professionals.</p>

              <h3>7. Intellectual Property</h3>
              <p>All content, features, and functionality of WBH are owned by us and protected by intellectual property laws. The AI models, algorithms, and analysis methodologies are proprietary.</p>

              <h3>8. Limitation of Liability</h3>
              <p>WBH shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service, including but not limited to health outcomes based on analysis results.</p>

              <h3>9. Modifications</h3>
              <p>We reserve the right to modify these terms at any time. Continued use of the App constitutes acceptance of updated terms.</p>
            </>
          ) : (
            <>
              <p className="modal-date">Last updated: March 13, 2026</p>
              <h3>1. Information We Collect</h3>
              <p><strong>Personal Information:</strong> Name, email address, and profile details you provide during registration.</p>
              <p><strong>Scan Data:</strong> Photos and images you submit for skin analysis. These are processed by our AI and stored securely to provide you with analysis history.</p>
              <p><strong>Usage Data:</strong> App interaction data, device information, and analytics to improve our service.</p>

              <h3>2. How We Use Your Data</h3>
              <p>Your data is used to: provide and improve skin analysis results, maintain your scan history, facilitate dermatologist consultations, and send relevant notifications (with your consent).</p>

              <h3>3. Data Security</h3>
              <p>We implement industry-standard encryption and security measures to protect your personal and medical data. Scan images are encrypted at rest and in transit. Access to your data is restricted to authorized personnel only.</p>

              <h3>4. Data Sharing</h3>
              <p>We do <strong>not</strong> sell your personal data. Data may be shared with: dermatologists you choose to consult with (only relevant scan data), third-party service providers who assist in operating our platform (under strict data protection agreements), and law enforcement when legally required.</p>

              <h3>5. Your Rights</h3>
              <p>You have the right to: access, correct, or delete your personal data, export your scan history, opt out of non-essential communications, and request account deletion at any time.</p>

              <h3>6. Data Retention</h3>
              <p>Your data is retained for as long as your account is active. Upon account deletion, personal data is removed within 30 days, though anonymized analytics data may be retained.</p>

              <h3>7. Cookies &amp; Tracking</h3>
              <p>We use essential cookies for authentication and preferences. Analytics cookies are used with your consent to improve the user experience.</p>

              <h3>8. Contact</h3>
              <p>For privacy concerns, contact us at <strong>privacy@wbh.com</strong>.</p>
            </>
          )}
        </div>
        <div className="modal-footer">
          <button className="btn btn-primary btn-block" onClick={onClose}>I Understand</button>
        </div>
      </div>
    </div>
  );
}

export default function SignupPage() {
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const [agreed, setAgreed] = useState(false);
  const [termsWarning, setTermsWarning] = useState(false);
  const [showTerms, setShowTerms] = useState<'terms' | 'privacy' | null>(null);
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [ageRange, setAgeRange] = useState('');
  const [country, setCountry] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const router = useRouter();
  const supabase = createClient();

  const handleSignup = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setTermsWarning(false);

    if (!agreed) {
      setTermsWarning(true);
      setError('Please accept the Terms of Service and Privacy Policy to continue');
      return;
    }
    if (!ageRange) {
      setError('Please select your age range');
      return;
    }
    if (!country) {
      setError('Please select your country');
      return;
    }
    if (password !== confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    if (password.length < 6) {
      setError('Password must be at least 6 characters');
      return;
    }

    setLoading(true);

    const { error: signUpError } = await supabase.auth.signUp({
      email: email.trim(),
      password,
      options: {
        data: {
          first_name: firstName.trim(),
          last_name: lastName.trim(),
          age_range: ageRange,
          country: country,
        },
        emailRedirectTo: `${window.location.origin}/auth/callback`,
      },
    });

    if (signUpError) {
      setError(signUpError.message);
      setLoading(false);
      return;
    }

    setSuccess(true);
    setLoading(false);
  };

  const handleOAuth = async (provider: 'google' | 'apple') => {
    await supabase.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: `${window.location.origin}/auth/callback`,
      },
    });
  };

  if (success) {
    return (
      <div className="auth-page">
        <div className="auth-container">
          <div className="auth-header">
            <img src="/images/wbhlogo.svg" alt="WBH" className="auth-logo-img" />
            <h1>Check Your Email</h1>
            <p>We&apos;ve sent a confirmation link to <strong>{email}</strong>. Click the link to activate your account.</p>
          </div>
          <div className="auth-form" style={{ textAlign: 'center' }}>
            <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: 20 }}>
              Didn&apos;t receive the email? Check your spam folder or try again.
            </p>
            <button className="btn btn-outline btn-block" onClick={() => setSuccess(false)}>
              Try Again
            </button>
          </div>
          <div className="auth-footer">
            Already have an account? <Link href="/login">Sign In</Link>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="auth-page">
      <div className="auth-container">
        <div className="auth-header">
          <img src="/images/wbhlogo.svg" alt="WBH" className="auth-logo-img" />
          <h1>Create Account</h1>
          <p>Start your AI-powered skin analysis journey</p>
        </div>
        <form className="auth-form" onSubmit={handleSignup}>
          {error && <div className="auth-error">{error}</div>}
          <div className="form-group">
            <label className="form-label">First Name</label>
            <div className="input-wrapper">
              <User size={18} className="input-icon" />
              <input type="text" className="form-input has-icon" placeholder="Enter your first name" value={firstName} onChange={(e) => setFirstName(e.target.value)} required />
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Last Name</label>
            <div className="input-wrapper">
              <User size={18} className="input-icon" />
              <input type="text" className="form-input has-icon" placeholder="Enter your last name" value={lastName} onChange={(e) => setLastName(e.target.value)} required />
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Email</label>
            <div className="input-wrapper">
              <Mail size={18} className="input-icon" />
              <input type="email" className="form-input has-icon" placeholder="Enter your email" value={email} onChange={(e) => setEmail(e.target.value)} required />
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Age Range</label>
            <div className="input-wrapper">
              <Calendar size={18} className="input-icon" />
              <select className="form-input has-icon" value={ageRange} onChange={(e) => setAgeRange(e.target.value)} required style={{ appearance: 'none', cursor: 'pointer' }}>
                <option value="" disabled>Select your age range</option>
                <option value="16-24">16 – 24</option>
                <option value="25-34">25 – 34</option>
                <option value="35-44">35 – 44</option>
                <option value="45-54">45 – 54</option>
                <option value="55+">55+</option>
              </select>
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Country</label>
            <div className="input-wrapper">
              <MapPin size={18} className="input-icon" />
              <select className="form-input has-icon" value={country} onChange={(e) => setCountry(e.target.value)} required style={{ appearance: 'none', cursor: 'pointer' }}>
                <option value="" disabled>Select your country</option>
                <option value="United Kingdom">United Kingdom</option>
                <option value="Nigeria">Nigeria</option>
                <option value="Ghana">Ghana</option>
                <option value="United States">United States</option>
                <option value="Canada">Canada</option>
                <option value="South Africa">South Africa</option>
                <option value="Kenya">Kenya</option>
                <option value="India">India</option>
                <option value="Australia">Australia</option>
                <option value="Germany">Germany</option>
                <option value="France">France</option>
                <option value="Brazil">Brazil</option>
                <option value="Jamaica">Jamaica</option>
                <option value="Trinidad and Tobago">Trinidad and Tobago</option>
                <option value="Sierra Leone">Sierra Leone</option>
                <option value="Cameroon">Cameroon</option>
                <option value="Ireland">Ireland</option>
                <option value="Other">Other</option>
              </select>
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Password</label>
            <div className="input-wrapper">
              <Lock size={18} className="input-icon" />
              <input
                type={showPassword ? 'text' : 'password'}
                className="form-input has-icon has-right-icon"
                placeholder="Create a password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
                minLength={6}
              />
              <button type="button" className="input-icon-right-btn" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>
          <div className="form-group">
            <label className="form-label">Confirm Password</label>
            <div className="input-wrapper">
              <Lock size={18} className="input-icon" />
              <input
                type={showConfirm ? 'text' : 'password'}
                className="form-input has-icon has-right-icon"
                placeholder="Confirm your password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                required
              />
              <button type="button" className="input-icon-right-btn" onClick={() => setShowConfirm(!showConfirm)} aria-label={showConfirm ? 'Hide password' : 'Show password'}>
                {showConfirm ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>
          <label className={`form-check ${termsWarning && !agreed ? 'terms-warning' : ''}`} style={{ marginBottom: 20 }}>
            <input type="checkbox" checked={agreed} onChange={(e) => { setAgreed(e.target.checked); setTermsWarning(false); setError(''); }} />
            {' '}I agree to the{' '}
            <button type="button" className="terms-link" onClick={() => setShowTerms('terms')}>Terms of Service</button>
            {' '}and{' '}
            <button type="button" className="terms-link" onClick={() => setShowTerms('privacy')}>Privacy Policy</button>
          </label>
          {termsWarning && !agreed && (
            <p style={{ color: '#C62828', fontSize: '0.82rem', fontWeight: 600, marginBottom: 12, marginTop: -8 }}>⚠ You must accept the terms to create an account</p>
          )}
          <button type="submit" className="btn btn-primary btn-block btn-lg" disabled={loading}>
            {loading ? <><Loader2 size={18} className="spin" /> Creating Account…</> : 'Create Account'}
          </button>
          <div className="form-divider">or sign up with</div>
          <div className="social-buttons">
            <button type="button" className="social-btn" style={{ width: '100%' }} onClick={() => handleOAuth('google')}>
              <img src="/icons/google.svg" alt="Google" width={20} height={20} /> Continue with Google
            </button>
          </div>
        </form>
        <div className="auth-footer">
          Already have an account? <Link href="/login">Sign In</Link>
        </div>
      </div>

      {showTerms && (
        <TermsModal tab={showTerms} onClose={() => setShowTerms(null)} />
      )}
    </div>
  );
}
