import type { Metadata } from 'next';
import Link from 'next/link';
import styles from '../legal.module.css';

export const metadata: Metadata = {
  title: 'Terms of Service — WBH Skin',
  description: 'The terms that apply when you use WBH Skin, the AI skin analysis platform by Wholesale Beauty Hub.',
};

const CONTACT_EMAIL = 'info@wholesalebeautyhub.co.uk';
const WBH_SITE = 'https://wholesalebeautyhub.co.uk';

export default function TermsPage() {
  return (
    <article>
      <h1>Terms of Service</h1>
      <p className={styles.updated}>Last updated: 4 October 2026</p>

      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) apply to your use of WBH Skin, the AI-powered skin
        analysis platform operated by Wholesale Beauty Hub (&ldquo;WBH&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;)
        (the &ldquo;Service&rdquo;). By creating an account or using the Service, you agree to these Terms.
        If you do not agree, please do not use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>WBH Skin lets you:</p>
      <ul>
        <li>scan or upload photos of your skin and receive an AI-generated skin analysis;</li>
        <li>keep a history of your scans and track changes over time;</li>
        <li>receive skincare and product recommendations;</li>
        <li>book consultations with skincare specialists; and</li>
        <li>register for WBH events.</li>
      </ul>
      <p>
        We may change, add or remove features from time to time. We will try to give you notice of any
        significant changes.
      </p>

      <h2>2. Not medical advice</h2>
      <div className={styles.callout}>
        <p style={{ marginBottom: 0 }}>
          Skin analysis results are generated by artificial intelligence and are for general information
          only. They are <strong>not a medical diagnosis</strong> and do not replace advice from a doctor or
          dermatologist. AI results can be wrong. Always speak to a qualified healthcare professional about
          any medical concern, and seek urgent care if you notice a changing mole, bleeding, rapidly spreading
          rash or any other worrying symptom.
        </p>
      </div>

      <h2>3. Who can use the Service</h2>
      <p>
        You must be at least 16 years old to use the Service. By using it, you confirm that you meet this
        requirement.
      </p>

      <h2>4. Your account</h2>
      <ul>
        <li>You must give accurate information when you sign up and keep it up to date.</li>
        <li>You are responsible for keeping your password safe and for activity on your account.</li>
        <li>You can sign up with an email address or sign in with Google or Apple.</li>
        <li>Tell us straight away at <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> if you think someone else has used your account.</li>
      </ul>

      <h2>5. Your photos and content</h2>
      <p>
        You keep ownership of the photos and information you submit. You give us permission to store and
        process them only so we can provide the Service to you, as described in our{' '}
        <Link href="/privacy">Privacy Policy</Link>. You can delete your scans at any time in the app.
      </p>
      <p>You agree to only submit photos:</p>
      <ul>
        <li>of yourself, or of someone who has given you permission;</li>
        <li>that do not contain nudity or offensive content; and</li>
        <li>that you have the right to share.</li>
      </ul>

      <h2>6. Consultations</h2>
      <p>
        Consultations booked through the Service are with independent skincare specialists. They are
        responsible for the advice they give. Please arrive on time and give notice if you need to cancel or
        rearrange.
      </p>

      <h2>7. Products and purchases</h2>
      <p>
        Product recommendations may link to the Wholesale Beauty Hub online store at{' '}
        <a href={WBH_SITE} target="_blank" rel="noopener noreferrer">wholesalebeautyhub.co.uk</a>. Purchases
        made there are covered by that store&rsquo;s own terms, delivery and returns policies. Always check the
        ingredients of a product and patch test before use, especially if you have sensitive skin or
        allergies.
      </p>

      <h2>8. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>use the Service for anything unlawful, harmful or misleading;</li>
        <li>upload photos of other people without their consent;</li>
        <li>try to access other users&rsquo; accounts or data;</li>
        <li>interfere with, overload or try to break the security of the Service;</li>
        <li>copy, scrape, reverse engineer or resell any part of the Service.</li>
      </ul>

      <h2>9. Our intellectual property</h2>
      <p>
        The Service, including its design, text, graphics, logos and software, belongs to WBH or our
        licensors. You may use it only for your own personal, non-commercial purposes.
      </p>

      <h2>10. Availability</h2>
      <p>
        We work to keep the Service running smoothly, but we cannot promise it will always be available or
        free of errors. We may suspend it for maintenance or for reasons outside our control.
      </p>

      <h2>11. Our liability</h2>
      <p>
        Nothing in these Terms limits our liability for death or personal injury caused by our negligence,
        for fraud, or for anything else that cannot be limited by law. Your legal rights as a consumer are
        not affected.
      </p>
      <p>
        Otherwise, we are not responsible for loss or damage that was not reasonably foreseeable, for
        decisions you make based on AI analysis results, or for the advice of independent specialists. The
        Service is provided for personal use, and we are not liable to you for any business losses.
      </p>

      <h2>12. Ending your use of the Service</h2>
      <p>
        You can stop using the Service and ask us to delete your account at any time by contacting us. We
        may suspend or close your account if you seriously or repeatedly break these Terms.
      </p>

      <h2>13. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. We will post the new version on this page and change
        the &ldquo;Last updated&rdquo; date. If the changes are significant, we will tell you by email or in the
        app. If you keep using the Service after the changes, you accept the new Terms.
      </p>

      <h2>14. Governing law</h2>
      <p>
        These Terms are governed by the laws of England and Wales. If you live in Scotland or Northern
        Ireland, you can also bring proceedings in your local courts.
      </p>

      <h2>15. Contact us</h2>
      <p>
        Wholesale Beauty Hub<br />
        Email: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
    </article>
  );
}
